version: "3.0"
services:
  mongo:
    image: mongo
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
  job-service:
    build: "../job-service"
    image: my/job-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"
  candidate-service:
    build: "../candidate-service"
    image: my/candidate-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
      - job-service
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
      job.service.url: "http://job-service:8080/job/"
  nginx:
    image: nginx
    depends_on:
      - candidate-service
      - job-service
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./html/index.html:/usr/share/nginx/html/index.html"