version: "3.0"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product
    volumes:
    - ./data:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
    - "8080:8080"

