# docker compose --profile=app up --build
version: "3.0"
services:
  mongo:
    image: mongo
    ports:
      - "${HOST_PORT:-27017}:27017"
    volumes:
      - ./src/test/resources/data:/docker-entrypoint-initdb.d
  candidate-service:
    build: .
    image: "candidate-service:wut"
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    profiles:
      - app
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
